version: "3.9"

services:
  translation-service:
    build: .
    image: igorkoishman/translation-app:latest
    container_name: translation-app
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    volumes:
      - data:/outputs
    restart: unless-stopped

volumes:
  data: