name: Build, Tag, and Push Multi-Service Docker Images

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-tag-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write  # for pushing tags
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR labels
        id: getlabels
        run: |
          echo "LABELS<<EOF" >> $GITHUB_ENV
          echo "${{ toJson(github.event.pull_request.labels) }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Determine version bump
        id: bump
        run: |
          LABELS="${{ toJson(github.event.pull_request.labels) }}"
          if [[ "$LABELS" == *"major"* ]]; then
            echo "BUMP=major" >> $GITHUB_ENV
          elif [[ "$LABELS" == *"minor"* ]]; then
            echo "BUMP=minor" >> $GITHUB_ENV
          else
            echo "BUMP=patch" >> $GITHUB_ENV
          fi

      - name: GitHub Tag Action
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"
          release_branches: "main"
          default_bump: ${{ env.BUMP }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push app image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            igorkoishman/translation-app:${{ steps.tag.outputs.new_tag }}
            igorkoishman/translation-app:latest
